<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function ($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                /*--- controller ---*/
                'BitlyV4_Context' => __DIR__ . '/BitlyV4_Context.php',
                /*--- END controller ---*/

                'namespace\\to\\the\\class' => __DIR__ . '/class_folder/class.php',
            );
        }
        $cn = trim($class);
        if (isset($classes[$cn])) {
            require $classes[$cn];
        }
    },
    true,
    false
);